In [8]:
#1. Import the NUMPY package under the name np.

import numpy as np

In [9]:
np.version.version

'1.16.2'

In [10]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,3,5))

print(a)

a.ndim

[[[0.03140479 0.62528927 0.85326256 0.05145176 0.75478184]
  [0.29218368 0.33599166 0.98156411 0.13213182 0.69329151]
  [0.43178533 0.22854433 0.79939255 0.1713876  0.4312428 ]]

 [[0.73197969 0.31298677 0.15421878 0.40937029 0.28364445]
  [0.05942749 0.77214491 0.71641768 0.72636525 0.61053966]
  [0.37501645 0.58220067 0.22083663 0.51722125 0.39734698]]]


3

In [11]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3),int)

print(b)

b.ndim

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


3

In [12]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)
print(b.size)

print(a.size == b.size)

30
30
True


In [13]:
#8. Are you able to add a and b? Why or why not?

print(a + b)

#THink this is cause to unequal dimensions shapes. 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [14]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b, (1,2,0))

print(c)



[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [15]:
d = a+c

print(d)
# The arrays with dimensions are equally shaped

[[[1.03140479 1.62528927 1.85326256 1.05145176 1.75478184]
  [1.29218368 1.33599166 1.98156411 1.13213182 1.69329151]
  [1.43178533 1.22854433 1.79939255 1.1713876  1.4312428 ]]

 [[1.73197969 1.31298677 1.15421878 1.40937029 1.28364445]
  [1.05942749 1.77214491 1.71641768 1.72636525 1.61053966]
  [1.37501645 1.58220067 1.22083663 1.51722125 1.39734698]]]


In [16]:
#12. Multiply a and c. Assign the result to e.

e = a*c

print(e)

[[[0.03140479 0.62528927 0.85326256 0.05145176 0.75478184]
  [0.29218368 0.33599166 0.98156411 0.13213182 0.69329151]
  [0.43178533 0.22854433 0.79939255 0.1713876  0.4312428 ]]

 [[0.73197969 0.31298677 0.15421878 0.40937029 0.28364445]
  [0.05942749 0.77214491 0.71641768 0.72636525 0.61053966]
  [0.37501645 0.58220067 0.22083663 0.51722125 0.39734698]]]


In [17]:
#13. Does e equal to a? Why or why not?

a == e 

#supposed to be equal. multiplied by 1. 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

In [18]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
print(d)


d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print('------------------------------')
print(d_max)
print(d_min)
print(d_mean)

[[[1.03140479 1.62528927 1.85326256 1.05145176 1.75478184]
  [1.29218368 1.33599166 1.98156411 1.13213182 1.69329151]
  [1.43178533 1.22854433 1.79939255 1.1713876  1.4312428 ]]

 [[1.73197969 1.31298677 1.15421878 1.40937029 1.28364445]
  [1.05942749 1.77214491 1.71641768 1.72636525 1.61053966]
  [1.37501645 1.58220067 1.22083663 1.51722125 1.39734698]]]
------------------------------
1.9815641073216645
1.0314047873921273
1.4561140856191286


In [19]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))

print(f)

[[[1.03140479 1.62528927 1.85326256 1.05145176 1.75478184]
  [1.29218368 1.33599166 1.98156411 1.13213182 1.69329151]
  [1.43178533 1.22854433 1.79939255 1.1713876  1.4312428 ]]

 [[1.73197969 1.31298677 1.15421878 1.40937029 1.28364445]
  [1.05942749 1.77214491 1.71641768 1.72636525 1.61053966]
  [1.37501645 1.58220067 1.22083663 1.51722125 1.39734698]]]


In [27]:
"""
16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
for i in range(d.shape[0]):
    for a in range(d.shape[1]):
        for b in range(d.shape[2]):
            if d[i,a,b] == d_max:
                f[i,a,b] = 100
            if d[i,a,b] == d_min:
                f[i,a,b] = 0    
            if d_min < d[i,a,b] < d_mean:
                f[i,a,b] = 25
            if d_mean < d[i,a,b] < d_max:
                f[i,a,b] = 75
            if f[i,a,b] == d_mean:
                f[i,a,b] = 50
                                           
print(f)             

[[[  0.  75.  75.  25.  75.]
  [ 25.  25. 100.  25.  75.]
  [ 25.  25.  75.  25.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 25.  75.  75.  75.  75.]
  [ 25.  75.  25.  75.  25.]]]
